#include "unity.h"
#include "monitoring.h"
#include "Mockdependency.h"   // generated by CMock

void setUp(void)
{
    // Called before each test
}

void tearDown(void)
{
    // Called after each test
}

void testfunc_should_double_the_dependency_value(void)
{
    // Arrange: mock dependency to return 5
    dependency_get_value_ExpectAndReturn(5);

    // Act
    int result = monitoring();

    // Assert
    TEST_ASSERT_EQUAL(10, result);
}

void testfunc_should_handle_zero(void)
{
    dependency_get_value_ExpectAndReturn(0);

    int result = monitoring();

    TEST_ASSERT_EQUAL(0, result);
}
